name: Example Workflow

on:
  workflow_call:
    inputs:
      example_input:
        required: true
        type: string
    secrets:
      example_secret:
        required: true

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Example Input
        run: echo "Input: ${{ inputs.example_input }}"
      - name: Echo Secret
        run: echo "Secret: ${{ secrets.example_secret }}"
